/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Report Draft
         * @description 리포트 본문 초안을 텍스트로 빠르게 생성한다 (파일 생성 없음).
         */
        post: operations["create_report_draft_v1_reports_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Report Document
         * @description 승인된 초안(content)을 실제 docx 파일로 변환해 반환한다.
         */
        post: operations["create_report_document_v1_reports_document_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ReportDocumentRequest
         * @description 승인된 초안을 실제 문서 파일로 변환하는 요청 스키마.
         */
        ReportDocumentRequest: {
            /**
             * Title
             * @description 문서 파일명(확장자 제외)
             */
            title: string;
            /**
             * Content
             * @description 문서에 그대로 포함할 리포트 본문(승인된 초안)
             */
            content: string;
            /**
             * Format
             * @description 문서 형식. 현재는 docx만 지원
             * @default docx
             * @constant
             */
            format: "docx";
        };
        /**
         * ReportDraftRequest
         * @description 리포트 초안(텍스트) 생성 요청 스키마.
         */
        ReportDraftRequest: {
            /**
             * Prompt
             * @description 리포트 생성을 위한 프롬프트
             */
            prompt: string;
            /**
             * Max Tokens
             * @description Claude 응답 최대 토큰 수. 미지정 시 설정값(anthropic_max_tokens) 사용
             */
            max_tokens?: number | null;
        };
        /**
         * ReportDraftResponse
         * @description 리포트 초안(텍스트) 생성 응답 스키마.
         */
        ReportDraftResponse: {
            /**
             * Content
             * @description Claude가 생성한 리포트 본문(텍스트)
             */
            content: string;
            /**
             * Suggested Title
             * @description 문서 파일명으로 쓰기 좋은 제안 값
             */
            suggested_title: string;
            /**
             * Input Tokens
             * @description 입력 토큰 수
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @description 출력 토큰 수
             */
            output_tokens: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_report_draft_v1_reports_draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_report_document_v1_reports_document_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportDocumentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
